site_name: zimmermatt
site_url: 'http://zimmermatt.github.io/'
repo_url: 'https://github.com/zimmermatt/zimmermatt.github.io'
edit_uri: ''
site_description: Thoughts on what's interesting to me at the moment...
site_author: Matt Zimmer
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>
remote_branch: master

strict: True

pages:
- Home: index.md

theme: material

extra:
  font:
    code: 'Menlo'

extra_css:
- css/custom.css

markdown_extensions:
- admonition
- codehilite
- pymdownx.tilde
- toc:
    permalink: True

